services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3301:3301"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'docker', '-d', 'myapp']
      interval: 5s
      timeout: 2s
      retries: 20

volumes:
  postgres_data: